### PR TITLE
Math

### PR DESCRIPTION
**Pull request by gypsydave5**
or Maths? Who can say?

Just spent two hours in a dark room with a sleeping baby banging this out again so let me know what you think...

### CODE REVIEW

**Comment by quii** [comment]
Nice one

Nearly there..

```

3.55s$ ./build.sh
math.md:1296:28: "inbetween" is a misspelling of "between"
math.md:2142:66: "valueable" is a misspelling of "valuable"
The command "./build.sh" exited with 123.
```

**Comment by quii** [comment]
PS Definitely "maths"

**Comment by gypsydave5** [comment]
Yer build script is somewhat reliant on not being a fork of yer repo

**Comment by quii** [comment]
1/5 See me

**Comment by gypsydave5** [comment]
That definitely wasn't like pulling teeth...

**Pull request merged**
