### PR TITLE
database/sql chapter (addresses #103)

### PR DESCRIPTION
**Pull request by djangulo**
Hi!

Thank you for this amazing book!

I've decided to tackle the `database/sql` chapter (addressing #103). I took the initial code you had in the `databases` branch and modified it.

It's turning out to be reaaaally wordy. 

# The plan

My plan was to:

1. Give a brief introduction to databases and why anyone would need one.
2. Add installation instructions for the DB of choice (PostgreSQL).
3. Explain database migrations, why they're important, and how to write a simple `go` program to handle them (no offloading to libraries), testing along the way.
4. Create CRUD operations for the `bookshelf` model, writing unit and integration tests along the way.
5. Close with an explanation that while integration tests are slow, this is what CI is really meant for. Then explain briefly what CI is and how it improves the development cycle.

## Inquiries

* You mention brevity in the contributing guidelines, I feel I'm breaking this rule by being so verbose. Yet databases are a deep and complex subject with a lot of branches; it feels inappropriate to start the chapter without some context. I've also added a lot of external links for further reading.
    * Should I hold back on the links? Maybe add a section at the end titled "further reading"?
* I ended up writing a lot of non-`go` code so far, mainly in the database setup. If this is unwelcome I can offload it to external guides. Please advise.
* The `Database Migrations` section is turning out to be a bit overlong, I feel that adding that and then a section on `CRUD` methods, with unit and integration tests, would turn out to be a very very long chapter.
    * Should it be split into several chapters instead?
        * If this would be the case, I believe naming the subsection "Integration tests" would be more appropriate.
    * In case it's too long, the migrations part can be gutted entirely, and focus only on the CRUD and database operation.

Thanks!

### CODE REVIEW

**Comment by djangulo** [comment]
Quick note:

During the `v4` rearrangement, `go mod` was throwing a fit because it was trying to get a package that did not exist (`github.com/djangulo/learn-go-with-tests/databases/v4`).

I had to make a new `go.mod` file so it would read my local packages as opposed to trying to fetch them from remote.

If and when this gets merged - that is, after it merges to `branch:databases,`, before it merges to `branch:master`, the `go.mod` file should be rebuilt by @quii and all occurrences of `github.com/djangulo` changed properly to `github.com/quii`.

**Comment by djangulo** [comment]
Alright! That was a lot longer than I initially expected.

I proofread it in bits and pieces here and there, and corrected every error I could find. I still want to do a final pass "as a reader" to validate the code snippets and the overall flow of the story, but I'll need a fresh brain and a cup of coffee before that :smile:.

I apologize for the length of it (which I presume you'll have to go through), but I saw no other way with all the stuff that had to be covered. I'm in no way done with it, and still open to suggestions.

Thanks again for your time and effort!

**Comment by quii** [comment]
Hey, just to let you know I am a busy boy right now (which is why the PRs in general are piling up). I appreciate your efforts and will try and find some time to read through this at some point. I'm not ignoring you!

**Comment by djangulo** [comment]
I never assumed you were ignoring me 😄 .

It's fine, of course, whenever you have the time. I'm well aware it's a bit long.

Thank you for letting me know!

**Comment by mikias** [comment]
@quii this is going stale...

**Comment by quii** [comment]
I know :( 

The good news is i have some holidays coming up mid december where i can have some time to go over it properly

@mikias Do you want to help? Have you read through it? Do you have any feedback?

**Comment by mikias** [comment]
I've read though it and thought it was a good fit for the book. I'll try and make sometime in the weekend to write up a detailed feedback for the pr. :)

**Comment by mikias** [comment]
A bit verbose but i think thats a good thing. Approved from my end 👍

**Comment by quii** [comment]
Hi @djangulo 

Again, apologies for not looking into this sooner, life is busy etc. I've spent the morning reading through this PR and I'm afraid in this current state I wont be merging this. 

## Overall feedback

- It's really, really long. I think it's totally legitimate to not cover the various error cases explicitly that crop up as they're all quite "boilerplatey". Of course acknowledge them, but say the reader can TDD through these problems if they wish. I don't think the reader will get much out of a lot of the content around this stuff. 
- The general approach I feel is not in keeping with the theme of the book of a behaviour driven, iterative approach. At various times you have multiple failing tests and doing large code changes.
- Sometimes you have a refactor section whilst the tests are failing. This is a big no no. 
- Occasionally you're not really practicing TDD. You have a section about "what if we create the same book twice?" and then you write some code to fix it rather than driving it with a test.

You wrote

> It's not entirely hopeless though, as a solution exists! It's along the lines of "run the tests on someone else's computer".
>
> Actually, it's exactly like "run the tests on someone else's computer", and it's called contionuous integration, commonly referred to as CI.

That's not really CI. CI is about continuously integrating code amongst a team. You talk about encouraging people to run integration tests on a separate server. I'm not sure how relevant that is to the chapter and a lot of people wouldn't agree with it anyway (on all projects I've worked on for a long time I run integration tests locally happily enough)

## Notes on approach

I feel like you go into abstractions too deeply, too quickly. 

If I were writing this chapter I'd probably only ever have integration tests around the kind of behaviour I need from a hypothetical bookcase package.

Paraphrasing a first test:

```go
store, close := Bookshelf.NewStore(testPostgresCreds)
defer close()
id, _ := store.Create(testBook)
retrievedBook, _ := store.Get(id)
assertBookEqual(testBook, retrievedBook)
```

This tests describes the behaviour that I, a user of the package needs - I don't want to care about migrations or the detail around it. 

Of course to make this test work I will have to write _some_ kind of migration thing to at least make a simple `Book` table, but to make the test pass it wouldn't be very clever or robust. But that's not the point, I'm using the behavioural test to drive _just the code I need_. 

Further on I might expand upon my migration needs and maybe I would extract it into something like what you've done, but it certainly wouldn't be what I would start with. In fact through developing I might decide that _actually_ I want to use a third-party lib to do migration. If that's the case I'm not burned too much because I haven't been writing a fully fledged thing (with tests) anyway. 

You start with doing a lot of work on migration (2k-ish lines of markdown) without a test _really_ motivating it. You're going too deep into implementation details rather than behaviour. There are other sections where you write tests to see what tables exist etc. Again, this is implementation detail that I wouldn't be testing against.

## Wrapping up

I'm sorry if this feels harsh and I hope you find the feedback constructive. If you wish to try and take the feedback onboard and give it another go you are of course welcome to raise a new PR. 

I am also happy to help you work through this. Maybe it would be less risky if you raised a PR with your first test and implementation and then i can give you feedback and you can keep working through the chapter with tighter feedback loops from me. You can message me on here or find me as quii on gopher slack. 

It's unfortunate that I didn't suggest contributors seek feedback from me sooner before sending an entire chapter so I'll update the contributing guidelines.

**Comment by StevenACoffman** [comment]
@djangulo I really feel like this is a very important contribution and I really hope you will make another attempt and not get discouraged. There are very few, if any, test driven database-Go tutorials, and I felt like it is very difficult to do well, especially working in isolation. Would you be interested in collaborating on one or several more incremental efforts?

**Comment by djangulo** [comment]
@quii your feedback is very welcome!

You make some very valid points.

There were too many tangents that contributed to the length of the text, and migrations were the biggest one of them all.

I'm curios if the way I handled the database cleanup is really the best way to do this. It feels as if I hammered _my solution_ into the text, and soon it started feeling clunky and slow. Perhaps testing in sqlite? The database shouldn't be a concern because, as you mentioned, it should be behavior being tested. This is one of those issues where trying to be clever ends up complicating things too much, sometimes locking you into an implementation (my `newTestPG` code probably wouldn't fly with any other database).

I'll be opening another PR soon, and as you said, take it slower, while keeping the feedback close.

And @StevenACoffman , yes, collaboration would be very welcome.

**Pull request closed without merging**
