### PR TITLE
describe integer types

### PR DESCRIPTION
**Pull request by guylyons**
a little desc of int types, could probably use some more detailing but thought i'd start the PR and see. or do you think it's unnecessary, even, to go in depth on this? thanks!

### CODE REVIEW

**Comment by quii** [comment]
Hey thanks for this

I am going to say no, _for now_. I am trying to make sure this thing is not simply a re-write of all of Go's documentation, but rather a way to learn go with tests.

What I mean by that is, it's better to introduce language features motivated by tests as I think that reinforces the knowledge more. 

So in this case, maybe you could show a test where using `int` wont work (i.e a very big number) and then show how using a different integer type could work. (e.g https://play.golang.org/p/UxOL-_VcakT)

What do you think?

**Comment by guylyons** [comment]
Yeah, I think that makes sense to keep in line with TDD instead of a rewrite. I'll follow up on your suggestion and see what I can come up with. 👍

**Comment by quii** [comment]
Awesome! Looking forward to it

I would just say though just to include the one example. Maybe show integer overflow and how `int64` can help you solve that. That shows the readers how there are different types of ints and then just link out to the official docs to show the reader where to learn the other ones. 

That saves you effort and keeps the chapter short and snappy :)

**Comment by guylyons** [comment]
Totally @quii ! I'll come back to this one, just been behind. Thanks!

**Comment by quii** [comment]
No worries, no rush :)

**Pull request closed without merging**
