### PR TITLE
Changes authored by Pamela Fox

### PR DESCRIPTION
**Pull request by gypsydave5**
(and a few by me)

This is easier than me trying to work through the diff which I failed at for the last twelve months.

The original PR is https://github.com/quii/learn-go-with-tests/pull/266

Apologies that it took so long.

Co-authored-by: Pamela Fox <pamela.fox@gmail.com>

### CODE REVIEW

**Comment by gypsydave5** [comment]
Urgh looks like I screwed up a rebase or a merge somewhere - @quii don't think this will break stuff

**Comment by quii** [comment]
Thanks, that's reassuring :D 
image

**Comment by quii** [comment]
`gypsydave5 wants to merge 82 commits into quii:master from gypsydave5:master`

You donkey, it needs to be on `main`. That's probably why the merge is so baffling.

**Comment by gypsydave5** [comment]
Christ I even thought I'd picked `main`

Try this.

**Pull request closed without merging**
