### PR TITLE
Use string literals in the case statements

### PR DESCRIPTION
**Pull request by pranavek**

### CODE REVIEW

**Comment by jeffre** [comment]
Perhaps you skipped the refactor step where you were supposed to add constants for those languages
`const spanish = "Spanish"`

**Comment by pranavek** [comment]
@jeffre I was not sure whether I should create a constant or not. Kept it as simple as possible.

**Comment by wobbol** [comment]
What section says to add constants for this? I missed it too :(

**Comment by jeffre** [comment]
Go to https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/hello-world and do ctrl+f for "const". It's the 9, 10, and 11th result for me.

**Comment by wobbol** [comment]
Thanks! I will do more legwork for my posts in the future.

**Comment by wobbol** [comment]
@pranavek Please close this PR. The book is not in error here.

**Pull request closed without merging**
