### PR TITLE
Traducao iteration

### PR DESCRIPTION
**Pull request by rafa-acioly**

### CODE REVIEW

**Comment by quii** [comment]
I think you meant to raise this in the translation repo by @larien ?

**Comment by larien** [comment]
I'm really sorry,  @quii
That happened because my repo is a fork from yours, so GitHub will set your repo as the base one when PRs are created
Is there any way to define the translation repo as the base one so we can avoid that?

**Comment by quii** [comment]
I would've assumed if OP had forked from _your_ repo it would've used yours as the base one? Not sure..

**Comment by larien** [comment]
We'll figure it out. I've sent a message to GitHub to see how we can fix that. Sorry for the inconvenience :sweat_smile:

**Comment by quii** [comment]
NP 👍

**Comment by rafa-acioly** [comment]
sorry @quii  :sweat_smile:

**Pull request closed without merging**
