### PR TITLE
Fix for epub rejected by Google Play Books, EPUBCheck

### PR DESCRIPTION
**Pull request by uppalabharath**
* Updated the build script to use latest pandoc image with latex support
* Fixed some minor issues in the marrkup and svg files
* Would fix the issue #420

### CODE REVIEW

**Comment by uppalabharath** [comment]
@quii Please review Thanks.

**Comment by quii** [comment]
I can't actually test this on my m1, but I'll YOLO it in, cut a release and see. Thanks @uppalabharath !

**Comment by uppalabharath** [comment]
@quii I see that the new release does not have the epub file attached as artefact. Could you please check if there is some error during book generation? 
Thanks

**Comment by quii** [comment]
Yes, this is because I moved the project away from Travis but haven't got around to setting it up so GH actions creates the book and puts it in a release. Still need to figure it out actually! Sorry, I will find time to look at this at some point, just struggling with other commitments right now

**Comment by uppalabharath** [comment]
@quii No worries.. 
Please let me know if there is any way I can help in setting up GH Actions.

**Pull request merged**
