### PR TITLE
PDF generation fixes

### PR DESCRIPTION
**Pull request by uppalabharath**
Issue: PDF generation build fixes
Issue link: https://github.com/quii/learn-go-with-tests/issues/205
Solution: 
1. Created a custom docker image with fonts needed for CJK support and some fonts
2. Updated the build script to use the custom pandoc image
Test case: 
1. Ran the build script locally and verified that the books generation is successful

### CODE REVIEW

**Comment by uppalabharath** [comment]
The fonts used does not support emojis and we would see the following warnings during PDF generation

```
Warning:  Missing character: There is no 🤷 (U+1F937) (U+1F937) in font DejaVu Sans/OT:script=latn;l
Warning:  Missing character: There is no ✅ (U+2705) (U+2705) in font DejaVu Sans/OT:script=latn;la
Warning:  Missing character: There is no ❓ (U+2753) (U+2753) in font DejaVu Sans/OT:script=latn;la
Warning:  Missing character: There is no ❓ (U+2753) (U+2753) in font DejaVu Sans/OT:script=latn;la
Warning:  Missing character: There is no ❓ (U+2753) (U+2753) in font DejaVu Sans/OT:script=latn;la
Warning:  Missing character: There is no ❓ (U+2753) (U+2753) in font DejaVu Sans/OT:script=latn;la
Warning:  Missing character: There is no ✅ (U+2705) (U+2705) in font DejaVu Sans/OT:script=latn;la
Warning:  Missing character: There is no ✅ (U+2705) (U+2705) in font DejaVu Sans/OT:script=latn;la
Warning:  Missing character: There is no ✅ (U+2705) (U+2705) in font DejaVu Sans/OT:script=latn;la
```

**Comment by uppalabharath** [comment]
@quii Please review

**Comment by uppalabharath** [comment]
Sample PDF generated
[learn-go-with-tests.pdf](https://github.com/quii/learn-go-with-tests/files/7548764/learn-go-with-tests.pdf)

**Comment by uppalabharath** [comment]
@quii I made changes to the github workflow file to attach the generated PDF and Epub files upon release publish. 

Please review and let me know your feedback
Thanks

**Comment by quii** [comment]
Wow this looks great, looking...

**Pull request merged**
