### PR TITLE
Chore: add _book/ to .gitignore

### PR DESCRIPTION
**Pull request by flw-cn**
Just for keep a clean work directory after `gitbook serve`.

### CODE REVIEW

**Comment by pityonline** [comment]
Thanks! This change will also prevent the side effect of `gitbook build`.

**Comment by pityonline** [comment]
@flw-cn Consider that someone using gitbook, maybe he generated some book locally with formats like mobi, epub, pdf. So is it better to import https://github.com/github/gitignore/blob/master/GitBook.gitignore?

**Comment by flw-cn** [comment]
Excellent idea!

Let me amend the commit at once.

**Comment by quii** [comment]
thanks all

**Pull request merged**
