### PR TITLE
Remove uncompilable if block from code example

### PR DESCRIPTION
**Pull request by Nickknack**
In the context exercise we update SpyStore to remove the cancel from the spy and just pass the context into the fetch. In one of the if statements of the happy path we reference store.ctx. 
Just removed the if statement to make the test actually run and pass like the instructions say.

### CODE REVIEW

**Comment by Nickknack** [comment]
`if store.ctx != request.Context() {
        t.Errorf("store was not passed through a context %v", store.ctx)
    }`
Is the if statement that doesn't compile. 

`type SpyStore struct {
	response string
	t        *testing.T
}`

Is how the SpyStore type is being defined in the previous step.

**Comment by quii** [comment]
Thanks for this, just a heads up that I'm not ignoring it and I'll be checking this out at some point this week

**Comment by Jragon** [comment]
You will need to update the test output too. 

```
=== RUN   TestServer/returns_data_from_store
--- FAIL: TestServer (0.00s)
    --- FAIL: TestServer/returns_data_from_store (0.00s)
    	context_test.go:22: got "", want "hello, world"
    	context_test.go:26: store was not passed through a context <nil>
```


should become

## Try to run the test

```
=== RUN   TestServer/returns_data_from_store
--- FAIL: TestServer (0.00s)
    --- FAIL: TestServer/returns_data_from_store (0.00s)
    	context_test.go:22: got "", want "hello, world"
```

related to #156

**Comment by Nickknack** [comment]
@Jragon @quii  ah, cool! If there's already an issue open for this, should I just close this pr?

**Comment by quii** [comment]
@Nickknack so sorry for taking long with this. Re the other bit, I'll fix that now

**Pull request merged**
