### PR TITLE
add persian

### PR DESCRIPTION
**Pull request by amghazanfari**
i add link to persian translation. it's not complete yet but we are working on it to complete it

### CODE REVIEW

**Comment by quii** [comment]
Nice!

**Comment by amghazanfari** [comment]
could you tell me why did you close the PR
is there any change that i must do?
@quii

**Comment by amghazanfari** [comment]
could you tell me why did you close the PR
is there any change that i must do?
@quii

**Comment by amghazanfari** [comment]
could you tell me why did you close the PR
is there any change that i must do?
@quii

**Comment by quii** [comment]
Sorry! Forgot to actually merge 🤣

**Pull request merged**
