### PR TITLE
Add Labels for Files and Folders

### PR DESCRIPTION
**Pull request by borenho**
First of all, thanks for the awesome tutorial! It's a masterpiece and can't say thank you enough for this Go into with TDD.

This PR makes it clearer for beginners the folders and files to put their code and tests. When I was starting, I had to look on Github the file names and their folders. Seniors could easily figure that out, but for beginners that may be a challenge and I hope to save them time thinking/checking Github.

I aim to do the same for more files (I am adding them as I study :))

### CODE REVIEW

**Comment by quii** [comment]
Hey

Thanks for the kind words and sorry for the slow reply. 

I dont think it's too important precisely what folder you work in. The idea is you start each chapter in a new folder and you can call it whatever you like; I dont really want to be very prescriptive. 

That said, if you found it a bit confusing you're probably not the only one. 

Rather than prescribing each specific folder, what do you think about adding some kind of generic instruction. "Make a new folder for each new chapter you work on"

**Comment by sanjib** [comment]
> The idea is you start each chapter in a new folder and you can call it whatever you like; I dont really want to be very prescriptive.

It's really nice to leave the folder naming choice to the end user. For example, when learning, I like to prefix my folders with a number so I can refer back to them more easily in the future. Works well for me but someone might prefer something else.

Here is an example, in a single project/repo, I have all the folders numbered sequentially corresponding to each topic/chapter:

image

**Comment by borenho** [comment]
@quii and @sanjib, I definitely agree with both of you - we should leave to the user the decision to create and name the folder/file whatever they like.

Earlier on, being a pretty new Gopher, I found it confusing that we didn't mention the what folder to have our files on. So to help out, it would be of great help to leave a generic instruction for users to make a new and descriptive folder for them to have their files on.

**Comment by quii** [comment]
Just committed a short note as discussed

**Pull request closed without merging**
