### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by jdsutherland**

### CODE REVIEW

**Comment by quii** [comment]
Hi

That's not a syntax error, you have trailing commas in Go :)

**Comment by jdsutherland** [comment]
Syntax error is the wrong description. The state of `StubPlayerStore` at that point has 3 fields so is the comma necessary?

**Comment by quii** [comment]
Not at a computer so cant verify but i think go lint or go fmt might demand it. I think ideally the fields would be on separate lines. That way if you add a new field the git diff isnt effected by the comma.

**Comment by jdsutherland** [comment]
On my end, gofmt removes the trailing comma when it's part of a single line. I think there's many other spots in the book where structs are initialized on a single line without a trailing comma, so this spot seems to stick out.

Really great resource by the way. Thanks for making this.

**Comment by quii** [comment]
I stand corrected!

**Pull request merged**
