### PR TITLE
Changed value to string

### PR DESCRIPTION
**Pull request by rhjensen79**
Got an error when trying the code. Had to change it to "string" for the Switch to work.

Might be a change to Go, since you wrote the guide. 
I ran it with Go 1.19

### CODE REVIEW

**Comment by quii** [comment]
Hi there

In the page, you'll find this line:

```go

const spanish = "Spanish"
```

This creates a constant, which we should use instead of the magic string.

**Comment by rhjensen79** [comment]
You are right @quii 
I did however go thru the documentation, several times, without getting it. 
So if you are ok with it, i will change my pull request, to make it more visible ?

**Comment by quii** [comment]
It seems this PR has changed a lot of the spacing in the file which makes it difficult to see what you've changed; plus it seems an unnecessary thing to do, could you revert back the spacing changes and just leave what you wish to change?

**Comment by rhjensen79** [comment]
You are right. Strange. I will close this one, and create a new one. 
It's more clean

**Pull request closed without merging**
